# Action Cable uses Redis by default to administer connections, channels, 
#  and sending/receiving messages over the WebSocket.

production:
  adapter: redis
  url: redis_db

development:
  # adapter: async
  adapter: redis
  url: redis://redis_db:6379

test:
  # adapter: async
  adapter: redis
  url: redis_db
