source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# ruby '2.3.0'
gem 'rails', '~> 5.2', '>= 5.2.4.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma'
# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.2'


gem 'jquery-rails', '>= 4.2.2'
gem 'turbolinks', '~> 5.x'
gem 'jbuilder', '~> 2.6', '>= 2.6.4'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'




group :production do 
  gem 'rails_12factor'
end


group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :development do
  gem 'web-console', '~> 3.4', '>= 3.4.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring', '>= 2.0.0'
  gem 'spring-watcher-listen', '~> 2.0.1'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
